#!/bin/sh

REPO="$1"
TXN="$2"

# TODO: need to check the policy on a commit message
#       wget ... %API%/svnPolicy/ ...
#       once done, update repo.sh to include pre-commit

svnlook log -t "$TXN" "$REPO" | grep "[a-zA-Z0-9]" >/dev/null || {
	echo "---------------------------------------------------------" >&2
	echo " Your commit message do not contain any meaningful text. " >&2
	echo "---------------------------------------------------------" >&2
	exit 1
}

#
# Subversion problem:
#  Hard to detect the tagging patterns and update patterns on a tag.
#
#svnlook changed -t "$TXN" "$REPO" | grep '^tags/' >/dev/null  && {
#	echo "----------------------------------------------------" >&2
#	echo " You are not allowed to change tags/*               " >&2 
#	echo "----------------------------------------------------" >&2
#	exit 1
#}
#

exit 0
