#!/bin/sh

REPOBASE="`basename "${1}"`"
USER="${2}"

ans="`wget -q -O- "%API%/projectHasMember/${REPOBASE}/${USER}" 2>/dev/null`"
[ "${ans}" = "YES" ] && exit 0

[ "${ans}" = "NO" ] && {
	echo "-------------------------------------------------------------" >&2
	echo " ${USER} is not a member of ${REPOBASE}" >&2
	echo "-------------------------------------------------------------" >&2
	exit 1
}

echo "---------------------------------------------------------------------" >&2
echo " Failed to check membership of ${REPOBASE} for ${USER}" >&2
echo "---------------------------------------------------------------------" >&2
exit 1
